### ISSUE TITLE
Could not connect to any of [('10.108.68.180', 9090)]

### ISSUE THREAD

**Issue by littlecomma** [BoyuanYan/TF4RSA#1]
Hello，Boyuan. I have studied spectrum allocation (SA) recently. Fortunately, I can learn SA through your code. But the result shows that `Could not connect to any of [('10.108.68.180', 9090)]` when I run your file. I have no idea and could you help me ? Thanks in advance！

**Comment by BoyuanYan** [comment]
Sorry about that this project has been deprecated long time ago, because I use pytorch to replace tensorflow. If you are interested in RSA, I can provide my previous RSA simulation by Java with comments in Chinese.

**Comment by littlecomma** [comment]
I am sorry to reply you so late. Could you send it to my e-mail：527769218@qq.com  .  Thank you so much！

**Comment by BoyuanYan** [comment]
@littlecomma Hope the source code could help you.
